// Textos de interfaz con id y aprobación (DR20). La fuente de la aprobación es docs/textos/registro-textos.md.
// Sin aprobar, el build muestra un marcador visible en vez del texto; en desarrollo se ve el texto.
const TEXTOS = {
  "nav.nombre": { texto: "Secciones", aprobado: true },
  "nav.mapa": { texto: "Mapa", aprobado: true },
  "nav.libro": { texto: "Libro", aprobado: true },
  "nav.experimentos": { texto: "Experimentos", aprobado: true },
  "nav.coach": { texto: "Coach", aprobado: true },
  "mapa.titulo": { texto: "Tu mapa", aprobado: true },
  "mapa.rotulo": { texto: "Tu diseño", aprobado: true },
  "anotacion.mapa.empieza": { texto: "empieza por aquí", aprobado: true },
  "anotacion.pegatina": { texto: "No es magia. Es diseño.", aprobado: true },
  "anotacion.titulo": { texto: "Nerd y proud", aprobado: true },
  "anotacion.manual": { texto: "tu manual de uso", aprobado: true },
  "anotacion.manual.cierre": { texto: "Léelo. Vívelo. Compártelo.", aprobado: true },
  "capitulo.en_curso": { texto: "Capítulo {numero} · {titulo}", aprobado: true },
  "capitulo.1.titulo": { texto: "Tu Tipo", aprobado: true },
  "capitulo.cambio": { texto: "Tu carta cambió por una corrección. Antes: {antes}. Ahora: {ahora}. Este capítulo se abre otra vez.", aprobado: true },
  "capitulo.2.titulo": { texto: "Tu Autoridad", aprobado: true },
  "capitulo.3.titulo": { texto: "Tu Perfil", aprobado: true },
  "capitulo.bloqueado": { texto: "El Capítulo {numero} · {titulo} se abre cuando completes el anterior.", aprobado: true },
  "chequeo.pregunta": { texto: "¿Cómo te fue?", aprobado: true },
  "chequeo.dia": { texto: "Día {dia} de lo que elegiste probar.", aprobado: true },
  "chequeo.me_representa": { texto: "Me representa", aprobado: true },
  "chequeo.no_me_representa": { texto: "No me representa", aprobado: true },
  "chequeo.no_probe": { texto: "No probé", aprobado: true },
  "chequeo.nota": { texto: "Nota para tu diario (opcional)", aprobado: true },
  "chequeo.sello": { texto: "Cerrado: {respuesta}", aprobado: true },
  "capitulo.fuente": { texto: "Fuente: {fuentes}", aprobado: true },
  "capitulo.borrador": { texto: "Borrador sin revisar", aprobado: true },
  "capitulo.elegir.titulo": { texto: "Elige cómo probarlo", aprobado: true },
  "capitulo.elegir.boton": { texto: "Elegir este", aprobado: true },
  "capitulo.elegido": { texto: "Lo elegiste el {fecha}.", aprobado: true },
  "capitulo.completado": { texto: "Capítulo completado", aprobado: true },
  "experimento.clase.experimento": { texto: "Experimento", aprobado: true },
  "experimento.clase.observacion": { texto: "Observación", aprobado: true },
  "experimento.aviso": { texto: "Un experimento no reemplaza el asesoramiento profesional ni se aplica a decisiones médicas, legales o financieras graves.", aprobado: true },
  "diario.titulo": { texto: "Tu diario", aprobado: true },
  "diario.rotulo": { texto: "Anota algo en tu diario", aprobado: true },
  "diario.guardar": { texto: "Guardar en mi diario", aprobado: true },
  "sync.falta_subir": { texto: "Falta subir", aprobado: true },
  "sync.sin_conexion": { texto: "Sin conexión", aprobado: true },
  "sync.servidor": { texto: "Servidor no disponible", aprobado: true },
  "sync.detalle.titulo": { texto: "Lo que falta subir", aprobado: true },
  "sync.detalle.linea": { texto: "{n} cambios guardados en este dispositivo esperan para subir.", aprobado: true },
  "ajustes.titulo": { texto: "Ajustes", aprobado: true },
  "ajustes.grupo.cuenta": { texto: "Cuenta", aprobado: true },
  "ajustes.cuenta.email": { texto: "Email", aprobado: true },
  "ajustes.cuenta.donde": { texto: "Dónde se guarda", aprobado: true },
  "ajustes.cuenta.donde.nube": { texto: "En la nube", aprobado: true },
  "ajustes.cuenta.donde.local": { texto: "Solo en este dispositivo", aprobado: true },
  "ajustes.grupo.carta": { texto: "Tu carta", aprobado: true },
  "ajustes.carta.nacimiento": { texto: "Datos de nacimiento", aprobado: true },
  "ajustes.carta.pais": { texto: "País donde vives", aprobado: true },
  "ajustes.carta.corregir": { texto: "Corregir mis datos", aprobado: true },
  "ajustes.grupo.apariencia": { texto: "Apariencia", aprobado: true },
  "ajustes.apariencia.tema": { texto: "Tema", aprobado: true },
  "ajustes.apariencia.automatico": { texto: "Automático", aprobado: true },
  "ajustes.apariencia.dia": { texto: "Día", aprobado: true },
  "ajustes.apariencia.noche": { texto: "Noche", aprobado: true },
  "ajustes.grupo.datos": { texto: "Datos", aprobado: true },
  "ajustes.datos.exportar": { texto: "Exportar mis datos", aprobado: true },
  "ajustes.datos.borrar": { texto: "Borrar cuenta", aprobado: true },
  "datos.exportar.titulo": { texto: "Exportar tus datos", aprobado: true },
  "datos.exportar.incluye": { texto: "Incluye tu carta, tu libro y tu diario. No incluye tu sesión ni tu clave de OpenRouter.", aprobado: true },
  "datos.exportar.boton": { texto: "Exportar", aprobado: true },
  "datos.exportar.preparando": { texto: "Preparando", aprobado: true },
  "datos.exportar.listo": { texto: "Listo para guardar", aprobado: true },
  "datos.exportar.vacio": { texto: "Nada que exportar", aprobado: true },
  "ajustes.datos.importar": { texto: "Importar un archivo", aprobado: true },
  "datos.importar.titulo": { texto: "Importar un archivo", aprobado: true },
  "datos.importar.elegir": { texto: "Elegir archivo", aprobado: true },
  "datos.importar.validando": { texto: "Validando", aprobado: true },
  "datos.importar.nuevo": { texto: "Nuevo", aprobado: true },
  "datos.importar.existe": { texto: "Ya existe", aprobado: true },
  "datos.importar.conflicto": { texto: "En conflicto", aprobado: true },
  "datos.importar.conflicto_nota": { texto: "Si una entrada choca, quedan las dos versiones.", aprobado: true },
  "datos.importar.combinar": { texto: "Combinar", aprobado: true },
  "datos.importar.listo": { texto: "Listo: se combinó con tus datos.", aprobado: true },
  "datos.importar.invalido": { texto: "Este archivo no es una exportación de DH Lab.", aprobado: true },
  "datos.importar.diario_cerrado": { texto: "Tu diario está cerrado en este navegador: sus entradas no se importan hasta que lo abras.", aprobado: true },
  "conflicto.etiqueta": { texto: "Versión de otro dispositivo", aprobado: true },
  "conflicto.explicacion": { texto: "Esta entrada se editó en dos dispositivos. Guardamos las dos para que no pierdas nada.", aprobado: true },
  "conflicto.quedarme_dos": { texto: "Quedarme con las dos", aprobado: true },
  "carta_cambio.titulo": { texto: "Tu carta cambió desde otro dispositivo", aprobado: true },
  "carta_cambio.ahora": { texto: "Ahora", aprobado: true },
  "carta_cambio.tu_correccion": { texto: "Tu corrección", aprobado: true },
  "carta_cambio.aplicar": { texto: "Aplicar mi corrección", aprobado: true },
  "carta_cambio.dejar": { texto: "Dejar la actual", aprobado: true },
  "datos.exportar.advertencia": { texto: "Tu diario sale sin cifrar: guarda el archivo en un lugar privado.", aprobado: true },
  "datos.exportar.diario_cerrado": { texto: "Tu diario está cerrado en este navegador y no se puede incluir hasta que lo abras.", aprobado: true },
  "ajustes.grupo.diario": { texto: "Diario", aprobado: true },
  "ajustes.diario.abierto": { texto: "Diario abierto en este navegador", aprobado: true },
  "recuperacion.titulo": { texto: "Tu código de recuperación", aprobado: true },
  "recuperacion.explicacion": { texto: "Con este código abres tu diario en otro dispositivo o si este navegador borra sus datos. Guárdalo fuera de la app: nadie más puede recuperarlo, ni siquiera Isma.", aprobado: true },
  "recuperacion.copiar": { texto: "Copiar", aprobado: true },
  "recuperacion.copiado": { texto: "Código copiado", aprobado: true },
  "recuperacion.copiar_fallo": { texto: "No se pudo copiar. Selecciona el código y cópialo a mano.", aprobado: true },
  "recuperacion.compartir": { texto: "Compartir", aprobado: true },
  "recuperacion.comprobar.rotulo": { texto: "Escribe los últimos 4 caracteres del código", aprobado: true },
  "recuperacion.comprobar.error": { texto: "No coinciden. Revisa el último grupo del código.", aprobado: true },
  "recuperacion.listo": { texto: "Listo", aprobado: true },
  "recuperacion.ahora_no": { texto: "Ahora no", aprobado: true },
  "recuperacion.pendiente.fila": { texto: "Falta guardar tu código de recuperación", aprobado: true },
  "recuperacion.pendiente.banner": { texto: "Todavía no guardaste tu código de recuperación.", aprobado: true },
  "recuperacion.generar_nuevo": { texto: "Generar código nuevo", aprobado: true },
  "recuperacion.generar_nuevo.aviso": { texto: "El código anterior dejará de servir.", aprobado: true },
  "recuperacion.reemplazado": { texto: "Este código fue reemplazado desde otro dispositivo", aprobado: true },
  "recuperacion.generar_otro": { texto: "Generar otro", aprobado: true },
  "diario.cerrado.fila": { texto: "Diario cerrado en este navegador", aprobado: true },
  "diario.cerrado.accion": { texto: "Escribir mi código", aprobado: true },
  "diario.desbloqueo.titulo": { texto: "Abre tu diario", aprobado: true },
  "diario.desbloqueo.rotulo": { texto: "Código de recuperación", aprobado: true },
  "diario.desbloqueo.abriendo": { texto: "Abriendo tu diario", aprobado: true },
  "diario.desbloqueo.error": { texto: "Ese código no abre tu diario", aprobado: true },
  "diario.no_tengo_codigo": { texto: "No tengo el código", aprobado: true },
  "diario.no_tengo.otro_dispositivo": { texto: "Si tienes el diario abierto en otro dispositivo, ve a Ajustes, Diario, y genera un código nuevo.", aprobado: true },
  "diario.nuevo": { texto: "Empezar un diario nuevo", aprobado: true },
  "diario.nuevo.confirmacion": { texto: "Vas a empezar un diario vacío. Las entradas anteriores se borran de tu cuenta.", aprobado: true },
  "diario.nuevo.boton": { texto: "Borrar y empezar de nuevo", aprobado: true },
  "diario.clave_reemplazada": { texto: "Empezaste un diario nuevo desde otro dispositivo. Escribe tu código de recuperación nuevo para sumar lo que escribiste aquí.", aprobado: true },
  "diario.anterior.titulo": { texto: "Este dispositivo todavía tiene tu diario anterior", aprobado: true },
  "diario.anterior.explicacion": { texto: "Empezaste un diario nuevo desde otro dispositivo. Puedes sumar estas entradas a tu diario nuevo o quitarlas de este dispositivo.", aprobado: true },
  "diario.anterior.recuperar": { texto: "Recuperarlo", aprobado: true },
  "diario.anterior.descartar": { texto: "Descartarlo", aprobado: true },
  "cuenta.salir.consecuencia": { texto: "Lo guardado en este dispositivo queda cerrado hasta que vuelvas a entrar.", aprobado: true },
  "cuenta.salir.consecuencia_local": { texto: "Para volver a entrar vas a necesitar conexión y tu email.", aprobado: true },
  "cuenta.borrar.titulo": { texto: "Borrar tu cuenta", aprobado: true },
  "cuenta.borrar.que_se_borra": { texto: "Se borran tu cuenta, tu carta, tu libro, tu diario y tus datos de uso, en este dispositivo y en nuestro servidor.", aprobado: true },
  "cuenta.borrar.diario": { texto: "Tu diario no se podrá recuperar.", aprobado: true },
  "cuenta.borrar.exportar": { texto: "Exportar primero", aprobado: true },
  "cuenta.borrar.boton": { texto: "Borrar mi cuenta", aprobado: true },
  "cuenta.borrando": { texto: "Borrando", aprobado: true },
  "cuenta.borrar.error": { texto: "Todavía no se pudo borrar", aprobado: true },
  "cuenta.borrar.error_detalle": { texto: "Lo que hay en este dispositivo sigue intacto hasta que el servidor confirme el borrado.", aprobado: true },
  "cuenta.borrar.sin_red": { texto: "Sin conexión: tu cuenta no se puede borrar ahora.", aprobado: true },
  "libro.vacio": { texto: "Tu libro se arma capítulo a capítulo. Todavía no hay ninguno.", aprobado: true },
  "experimentos.tarjeta": { texto: "Experimento de la semana", aprobado: true },
  "experimentos.sello": { texto: "¡Prueba esto!", aprobado: true },
  "interruptor.responder": { texto: "Responder", aprobado: true },
  "interruptor.iniciar": { texto: "Iniciar", aprobado: true },
  "comun.si": { texto: "Sí", aprobado: true },
  "comun.no": { texto: "No", aprobado: true },
  "experimentos.vacio": { texto: "Todavía no elegiste ningún experimento.", aprobado: true },
  "ia.banner.cerca": { texto: "Te queda poco uso de la IA incluida.", aprobado: true },
  "ia.no_entra": { texto: "Este capítulo no entra en lo que te queda de IA incluida.", aprobado: true },
  "ia.renovacion": { texto: "Se renueva el {fecha}.", aprobado: true },
  "ia.pausa": { texto: "La IA incluida está en pausa", aprobado: true },
  "ia.pausa.clave": { texto: "Puedes seguir con tu clave de OpenRouter.", aprobado: true },
  "ia.consentimiento.titulo": { texto: "Antes de usar la IA", aprobado: true },
  "ia.consentimiento.que_recibe": { texto: "La IA recibe los atributos de tu carta (Tipo, Autoridad, Perfil, Centros y Canales), las fichas que corresponden y lo que escribes en el chat. Nunca tu fecha, hora ni lugar de nacimiento, ni tu diario.", aprobado: true },
  "ia.consentimiento.incluida": { texto: "Con la IA incluida, tus pedidos pasan por nuestro servidor hacia OpenRouter, en Estados Unidos, y no se guardan.", aprobado: true },
  "ia.consentimiento.aceptar": { texto: "Acepto", aprobado: true },
  "ia.mantener_abierta": { texto: "Mantén esta app abierta mientras se escribe tu capítulo", aprobado: true },
  "ia.corte": { texto: "El capítulo no se publicó; este intento contó para tu tope", aprobado: true },
  "ajustes.grupo.ia": { texto: "IA", aprobado: true },
  "ajustes.ia.incluida": { texto: "IA incluida", aprobado: true },
  "ajustes.ia.disponible": { texto: "Disponible", aprobado: true },
  "ajustes.ia.cerca": { texto: "Cerca del tope", aprobado: true },
  "ajustes.ia.pausa": { texto: "En pausa", aprobado: true },
  "ia.capitulo.escribir": { texto: "Escribir este capítulo con IA", aprobado: true },
  "ia.capitulo.reescribir": { texto: "Escribirlo otra vez", aprobado: true },
  "ia.capitulo.etapa": { texto: "Escribiendo y verificando tu capítulo", aprobado: true },
  "ia.capitulo.no_publicable": { texto: "No pudimos escribir un capítulo que pase las verificaciones. Puedes reintentar o leer las fichas, que están abajo.", aprobado: true },
  "ia.insignia": { texto: "Cada afirmación fue contrastada automáticamente con las fichas citadas. No es una revisión humana.", aprobado: true },
  "ia.desactualizado": { texto: "Este texto quedó desactualizado: cambió una de sus fichas.", aprobado: true },
  "ia.error": { texto: "La IA no respondió. Intenta de nuevo.", aprobado: true },
  "coach.rotulo": { texto: "Escribe tu pregunta", aprobado: true },
  "coach.enviar": { texto: "Enviar", aprobado: true },
  "coach.pensando": { texto: "Pensando", aprobado: true },
  "coach.tu": { texto: "Tú", aprobado: true },
  "coach.sin_biblioteca": { texto: "Eso todavía no lo tengo en mi biblioteca.", aprobado: true },
  "coach.aclaracion": { texto: "El coach cita sus fuentes, pero sus respuestas no pasan por el verificador del libro.", aprobado: true },
  "coach.sensible": { texto: "Con esto no puedo ayudarte desde tu carta. Para temas de salud, de crisis o decisiones legales o financieras importantes, busca a una persona profesional o a alguien de tu confianza. Los recursos de ayuda de cada país todavía no están cargados en la app.", aprobado: true },
  "coach.ciencia": { texto: "No. El Diseño Humano no es una ciencia ni está comprobado. Aquí lo usas como un experimento personal: pruebas y miras qué te sirve.", aprobado: true },
  "coach.anotar": { texto: "Anotar en mi diario", aprobado: true },
  "coach.anotado": { texto: "Anotado en tu diario", aprobado: true },
  "coach.vacio": { texto: "El coach todavía no está disponible.", aprobado: true },
  "mapa.nombre": { texto: "Mapa de tu carta", aprobado: true },
  "mapa.centro.definido": { texto: "definido", aprobado: true },
  "mapa.centro.indefinido": { texto: "indefinido", aprobado: true },
  "mapa.candado": { texto: "{elemento} se abre en el Capítulo {numero}: {titulo}.", aprobado: true },
  "mapa.centro.canales": { texto: "Canales de este Centro", aprobado: true },
  "mapa.canal": { texto: "Canal {a}-{b}", aprobado: true },
  "mapa.canal.definido": { texto: "definido", aprobado: true },
  "mapa.canal.media": { texto: "tienes la Puerta {puerta}", aprobado: true },
  "mapa.canal.indefinido": { texto: "sin Puertas activas", aprobado: true },
  "capitulo.4.titulo": { texto: "Tus Centros", aprobado: true },
  "capitulo.5.titulo": { texto: "Tus Canales", aprobado: true },
  "hoja.titulo": { texto: "Guarda tu carta", aprobado: true },
  "hoja.email.rotulo": { texto: "Tu email", aprobado: true },
  "hoja.email.error": { texto: "Revisa tu email: parece incompleto.", aprobado: true },
  "hoja.casilla": { texto: "Acepto los términos", aprobado: true },
  "hoja.link_terminos": { texto: "Términos", aprobado: true },
  "hoja.link_politica": { texto: "Política de privacidad", aprobado: true },
  "hoja.casilla.error": { texto: "Marca la casilla para seguir.", aprobado: true },
  "hoja.boton": { texto: "Enviarme el código de acceso", aprobado: true },
  "hoja.enviando": { texto: "Enviando el código de acceso", aprobado: true },
  "hoja.solo_local": { texto: "Prefiero guardarla solo en este dispositivo", aprobado: true },
  "hoja.cierre": { texto: "Tu carta quedó guardada.", aprobado: true },
  "hoja.empezar_capitulo": { texto: "Empezar el Capítulo 1", aprobado: true },
  "solo_local.titulo": { texto: "Solo en este dispositivo", aprobado: true },
  "solo_local.promesa": { texto: "Tu carta, tu libro, tu diario y tus conversaciones con el coach no se guardan en nuestro servidor.", aprobado: true },
  "solo_local.linea_cuenta": { texto: "Igual necesitas una cuenta con tu email.", aprobado: true },
  "solo_local.linea_ia": { texto: "Si usas la IA incluida, tus pedidos pasan por nuestro servidor, pero no se guardan.", aprobado: true },
  "solo_local.linea_safari": { texto: "En iPhone, Safari puede borrar los datos después de 7 días sin abrir la app.", aprobado: true },
  "solo_local.linea_otra_compu": { texto: "Para usar tu cuenta en otra computadora, tendrás que exportar e importar tus datos.", aprobado: true },
  "solo_local.accion": { texto: "Guardar solo en este dispositivo", aprobado: true },
  "solo_local.volver": { texto: "Volver", aprobado: true },
  "a_local.confirmar": { texto: "Pasar a solo en este dispositivo", aprobado: true },
  "a_local.etapa.subiendo": { texto: "Subiendo lo pendiente", aprobado: true },
  "a_local.etapa.bajando": { texto: "Bajando y verificando: {hechas} de {total}", aprobado: true },
  "a_local.etapa.borrando": { texto: "Borrando la copia del servidor", aprobado: true },
  "a_local.etapa.listo": { texto: "Listo", aprobado: true },
  "almacenamiento.escritura_bloqueada": { texto: "Mientras termina el cambio, no se puede escribir.", aprobado: true },
  "almacenamiento.sin_red": { texto: "Sin conexión: el cambio no puede empezar.", aprobado: true },
  "almacenamiento.comprobando": { texto: "Comprobando el cambio", aprobado: true },
  "almacenamiento.fallo": { texto: "El cambio no terminó. Tus datos siguen en la nube y no se borró nada.", aprobado: true },
  "a_local.otros.banner": { texto: "Tu cuenta dejó de guardarse en la nube. Lo que hay en este dispositivo se queda aquí.", aprobado: true },
  "a_local.otros.exportar": { texto: "Tienes cambios que no llegaron a la nube. Expórtalos para llevarlos a tu otro dispositivo.", aprobado: true },
  "a_nube.titulo": { texto: "Guardar en la nube", aprobado: true },
  "a_nube.lineas": { texto: "Tu carta y tu libro se guardan en nuestro servidor, donde Isma puede verlos. Tu diario se cifra en tu dispositivo. Nadie más puede leerlo, ni siquiera Isma.", aprobado: true },
  "a_nube.codigo": { texto: "Al terminar vas a recibir un código de recuperación para abrir tu diario en otros dispositivos.", aprobado: true },
  "a_nube.confirmar": { texto: "Pasar a la nube", aprobado: true },
  "a_nube.subiendo": { texto: "Subiendo: {hechas} de {total}", aprobado: true },
  "a_nube.parcial": { texto: "La subida se cortó. Sigue donde quedó en cuanto haya conexión.", aprobado: true },
  "a_nube.otros.banner": { texto: "Tu cuenta ahora se guarda en la nube. Estamos subiendo lo que hay en este dispositivo.", aprobado: true },
  "a_nube.otros.diario": { texto: "Para subir tu diario, escribe tu código de recuperación.", aprobado: true },
  "acceso.entrar.titulo": { texto: "Entra con tu email", aprobado: true },
  "acceso.titulo": { texto: "Escribe tu código de acceso", aprobado: true },
  "acceso.enviado_a": { texto: "Te lo enviamos a {email}.", aprobado: true },
  "acceso.cambiar_email": { texto: "Cambiar email", aprobado: true },
  "acceso.rotulo": { texto: "Código de acceso (6 dígitos)", aprobado: true },
  "acceso.verificando": { texto: "Verificando", aprobado: true },
  "acceso.incorrecto": { texto: "Ese código no es correcto. Te quedan {n} intentos.", aprobado: true },
  "acceso.vencido": { texto: "Este código de acceso venció.", aprobado: true },
  "acceso.agotado": { texto: "Usaste todos los intentos de este código.", aprobado: true },
  "acceso.pedir_otro": { texto: "Pedir otro código", aprobado: true },
  "acceso.reenviar": { texto: "Reenviar", aprobado: true },
  "acceso.reenviar_espera": { texto: "Podrás reenviarlo en {tiempo}.", aprobado: true },
  "acceso.sin_red": { texto: "Sin conexión. Revisa tu red e inténtalo otra vez.", aprobado: true },
  "acceso.guardando": { texto: "Guardando tu carta", aprobado: true },
  "acceso.trayendo": { texto: "Trayendo tu carta", aprobado: true },
  "acceso.solo_local_aqui": { texto: "Tu cuenta guarda todo solo en otro dispositivo. Para traer tus datos aquí, importa el archivo que exportaste allí.", aprobado: true },
  "acceso.solo_local_importar": { texto: "Importar un archivo", aprobado: true },
  "invitacion.titulo": { texto: "Este email todavía no tiene invitación", aprobado: true },
  "invitacion.que_paso": { texto: "Por ahora, la app es solo para personas invitadas.", aprobado: true },
  "invitacion.como_pedir": { texto: "Pídele una invitación a quien te compartió este link o escribe a hola@ismaelbriasco.com.", aprobado: true },
  "invitacion.carta_guardada": { texto: "Tu carta queda guardada en este navegador para cuando llegue tu invitación.", aprobado: true },
  "invitacion.otro_email": { texto: "Probar con otro email", aprobado: true },
  "rescate.envio_email": { texto: "No pudimos mandarte el email", aprobado: true },
  "rescate.demasiados": { texto: "Espera unos minutos", aprobado: true },
  "rescate.sesion_vencida": { texto: "Tu sesión venció. Vuelve a entrar.", aprobado: true },
  "rescate.esquema_nuevo": { texto: "Actualiza la app", aprobado: true },
  "comun.reintentar": { texto: "Reintentar", aprobado: true },
  "comun.volver": { texto: "Volver", aprobado: true },
  "comun.cerrar": { texto: "Cerrar", aprobado: true },
  "comun.deshacer": { texto: "Deshacer", aprobado: true },
  "comun.cancelar": { texto: "Cancelar", aprobado: true },
  "acceso.incorrecto_uno": { texto: "Ese código no es correcto. Te queda 1 intento.", aprobado: true },
  "bienvenida.frase": { texto: "Calcula tu carta de Diseño Humano, descúbrela jugando y arma tu propio libro.", aprobado: true },
  "bienvenida.empezar": { texto: "Empezar", aprobado: true },
  "bienvenida.solo_invitacion": { texto: "Por ahora, solo con invitación", aprobado: true },
  "bienvenida.ya_tengo_cuenta": { texto: "Ya tengo cuenta", aprobado: true },
  "cuenta.salir": { texto: "Salir", aprobado: true },
  "cuenta.saliendo": { texto: "Saliendo", aprobado: true },
  "cuenta.salir.error": { texto: "No pudimos cerrar tu sesión en el servidor.", aprobado: true },
  "nacimiento.paso": { texto: "Paso {n} de 3", aprobado: true },
  "nacimiento.promesa": { texto: "Tus datos se quedan en este navegador hasta que guardes tu carta.", aprobado: true },
  "nacimiento.fecha.titulo": { texto: "¿Cuándo naciste?", aprobado: true },
  "nacimiento.fecha.rotulo": { texto: "Fecha de nacimiento", aprobado: true },
  "nacimiento.fecha.error": { texto: "Elige tu fecha de nacimiento.", aprobado: true },
  "nacimiento.hora.titulo": { texto: "¿A qué hora naciste?", aprobado: true },
  "nacimiento.hora.rotulo": { texto: "Hora de nacimiento", aprobado: true },
  "nacimiento.hora.confiabilidad": { texto: "¿Qué tan segura es esa hora?", aprobado: true },
  "nacimiento.hora.exacta": { texto: "Exacta: la saqué de la partida o del certificado", aprobado: true },
  "nacimiento.hora.aproximada": { texto: "Aproximada", aprobado: true },
  "nacimiento.hora.desconocida": { texto: "No la sé", aprobado: true },
  "nacimiento.hora.margen": { texto: "Minutos de margen, para antes y para después", aprobado: true },
  "nacimiento.hora.error": { texto: "Escribe la hora o elige que no la sabes.", aprobado: true },
  "nacimiento.lugar.titulo": { texto: "¿Dónde naciste?", aprobado: true },
  "nacimiento.lugar.pais": { texto: "País de nacimiento", aprobado: true },
  "nacimiento.lugar.ciudad": { texto: "Ciudad o localidad", aprobado: true },
  "nacimiento.lugar.cargando": { texto: "Cargando localidades", aprobado: true },
  "nacimiento.lugar.sin_resultados": { texto: "No encontramos esa localidad. Prueba con la ciudad más cercana.", aprobado: true },
  "nacimiento.lugar.error": { texto: "Elige tu localidad de la lista.", aprobado: true },
  "nacimiento.residencia.rotulo": { texto: "País donde vives hoy", aprobado: true },
  "nacimiento.residencia.ayuda": { texto: "Lo usamos solo para mostrarte recursos de ayuda de tu país.", aprobado: true },
  "nacimiento.siguiente": { texto: "Siguiente", aprobado: true },
  "nacimiento.listo": { texto: "Calcular mi carta", aprobado: true },
  "configuracion.titulo": { texto: "Tu configuración", aprobado: true },
  "configuracion.tipo": { texto: "Tipo", aprobado: true },
  "configuracion.estrategia": { texto: "Estrategia", aprobado: true },
  "configuracion.autoridad": { texto: "Autoridad", aprobado: true },
  "autoridad.emocional": { texto: "Emocional", aprobado: true },
  "autoridad.sacral": { texto: "Sacral", aprobado: true },
  "autoridad.esplenica": { texto: "Esplénica", aprobado: true },
  "autoridad.ego_manifestado": { texto: "Ego manifestado", aprobado: true },
  "autoridad.ego_proyectado": { texto: "Ego proyectado", aprobado: true },
  "autoridad.autoproyectada": { texto: "Autoproyectada", aprobado: true },
  "autoridad.mental": { texto: "Mental", aprobado: true },
  "autoridad.lunar": { texto: "Lunar", aprobado: true },
  "configuracion.perfil": { texto: "Perfil", aprobado: true },
  "configuracion.definicion": { texto: "Definición", aprobado: true },
  "configuracion.centros": { texto: "Centros definidos", aprobado: true },
  "configuracion.canales": { texto: "Canales", aprobado: true },
  "configuracion.firma": { texto: "Firma", aprobado: true },
  "configuracion.no_yo": { texto: "No-Yo", aprobado: true },
  "configuracion.de": { texto: "{n} de {total}", aprobado: true },
  "configuracion.o": { texto: " o ", aprobado: true },
  "tipo.manifestador": { texto: "Manifestador", aprobado: true },
  "tipo.generador": { texto: "Generador", aprobado: true },
  "tipo.generador_manifestante": { texto: "Generador Manifestante", aprobado: true },
  "tipo.proyector": { texto: "Proyector", aprobado: true },
  "tipo.reflector": { texto: "Reflector", aprobado: true },
  "estrategia.responder": { texto: "Esperar para responder", aprobado: true },
  "estrategia.invitacion": { texto: "Esperar la invitación", aprobado: true },
  "estrategia.informar": { texto: "Informar", aprobado: true },
  "estrategia.ciclo_lunar": { texto: "Esperar un ciclo lunar", aprobado: true },
  "firma.satisfaccion": { texto: "Satisfacción", aprobado: true },
  "firma.exito": { texto: "Éxito", aprobado: true },
  "firma.paz": { texto: "Paz", aprobado: true },
  "firma.sorpresa": { texto: "Sorpresa", aprobado: true },
  "no_yo.frustracion": { texto: "Frustración", aprobado: true },
  "no_yo.amargura": { texto: "Amargura", aprobado: true },
  "no_yo.ira": { texto: "Ira", aprobado: true },
  "no_yo.decepcion": { texto: "Decepción", aprobado: true },
  "definicion.ninguna": { texto: "Sin definición", aprobado: true },
  "definicion.simple": { texto: "Simple", aprobado: true },
  "definicion.partida": { texto: "Partida", aprobado: true },
  "definicion.triple": { texto: "Triple partida", aprobado: true },
  "definicion.cuadruple": { texto: "Cuádruple partida", aprobado: true },
  "hora.repetida.titulo": { texto: "Esa hora ocurrió dos veces", aprobado: true },
  "hora.repetida.explicacion": { texto: "Ese día el reloj se atrasó una hora, así que las {hora} pasaron dos veces. ¿Cuál fue la tuya?", aprobado: true },
  "hora.repetida.primera": { texto: "La primera vez, antes del cambio", aprobado: true },
  "hora.repetida.segunda": { texto: "La segunda vez, después del cambio", aprobado: true },
  "hora.inexistente.titulo": { texto: "Esa hora no existió", aprobado: true },
  "hora.inexistente.explicacion": { texto: "Ese día el reloj se adelantó y las {hora} no ocurrieron. Revisa la hora de tu nacimiento.", aprobado: true },
  "hora.corregir": { texto: "Corregir la hora", aprobado: true },
  "hora.pendiente.titulo": { texto: "Tu carta depende de la hora", aprobado: true },
  "hora.pendiente.explicacion": { texto: "Con la hora que diste hay más de una carta posible, y cambia tu Tipo. Para seguir necesitamos la hora exacta.", aprobado: true },
  "hora.pendiente.donde": { texto: "Búscala en tu partida o en tu certificado de nacimiento.", aprobado: true },
  "hora.posibilidad": { texto: "De {desde} a {hasta}: {tipo}, perfil {perfil}", aprobado: true },
  "hora.pendiente.explicacion_autoridad": { texto: "Con la hora que diste hay más de una carta posible, y cambia tu Autoridad. Para seguir necesitamos la hora exacta.", aprobado: true },
  "hora.posibilidad_autoridad": { texto: "De {desde} a {hasta}: {tipo}, Autoridad {autoridad}, perfil {perfil}", aprobado: true },
  "hora.incierta.nota": { texto: "Espera tu hora", aprobado: true },
  "hora.incierta.explicacion": { texto: "Algunas piezas de tu carta cambian según la hora exacta. Las marcamos hasta que la confirmes.", aprobado: true },
  "revelacion.titulo": { texto: "Tu carta está lista", aprobado: true },
  "revelacion.encender": { texto: "Encender", aprobado: true },
  "revelacion.saltear": { texto: "Saltar", aprobado: true },
  "revelacion.sonido": { texto: "Sonido", aprobado: true },
  "revelacion.cierre": { texto: "Esta es tu carta.", aprobado: true },
} as const;

export type TextoId = keyof typeof TEXTOS;

export function t(id: TextoId, valores: Record<string, string | number> = {}, desarrollo: boolean = import.meta.env.DEV): string {
  const { texto, aprobado } = TEXTOS[id];
  if (!aprobado && !desarrollo) return `⟦${id}⟧`;
  const listo = texto.replace(/\{(\w+)\}/g, (_, k: string) => String(valores[k] ?? `{${k}}`));
  return listo;
}
